// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CodeMessage.proto

#ifdef _MSC_VER
	#pragma warning(push)
	#pragma warning(disable : 4125)
	#pragma warning(disable : 4668)
	#pragma warning(disable : 4800)
	#pragma warning(disable : 4647)
#endif

#include "CodeMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace KFMsg {
}  // namespace KFMsg
namespace protobuf_CodeMessage_2eproto {
void InitDefaults() {
}

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "CodeMessage.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\021CodeMessage.proto\022\005KFMsg*\317\005\n\017ProjectCo"
      "deEnum\022\016\n\nLogicError\020\000\022\022\n\014HeroNotExist\020\231"
      "\362\001\022\022\n\014HeroNotFight\020\232\362\001\022\024\n\016EffectNotExist"
      "\020\233\362\001\022\022\n\014FootNotExist\020\234\362\001\022\024\n\016MatchRequest"
      "Ok\020\201\372\001\022\026\n\020MatchAlreadyWait\020\202\372\001\022\021\n\013MatchI"
      "nRoom\020\203\372\001\022\025\n\017MatchNotInMatch\020\204\372\001\022\023\n\rMatc"
      "hCancelOk\020\205\372\001\022\030\n\022MatchAffirmTimeout\020\207\372\001\022"
      "\031\n\023MatchNotFighterHero\020\210\372\001\022\024\n\016MatchDataE"
      "rror\020\211\372\001\022\027\n\021MatchRoomNotExist\020\212\372\001\022\025\n\017Mat"
      "chRoomIsFull\020\213\372\001\022\034\n\026MatchRoomPasswordErr"
      "or\020\214\372\001\022\026\n\020MatchRoomIdError\020\215\372\001\022\033\n\025MatchR"
      "oomVersionError\020\216\372\001\022\032\n\024MatchRoomJoinAlre"
      "ady\020\217\372\001\022\034\n\026MatchRoomKickTypeError\020\220\372\001\022\031\n"
      "\023MatchRoomKickMaster\020\221\372\001\022\035\n\027MatchRoomPla"
      "yerNoInRoom\020\222\372\001\022\036\n\030MatchRoomStartCanNotK"
      "ick\020\223\372\001\022\032\n\024MatchRoomFightMaster\020\224\372\001\022\031\n\023M"
      "atchRoomNotPrepare\020\225\372\001\022\037\n\031MatchRoomPrepa"
      "reTypeError\020\226\372\001\022\034\n\026MatchRoomCanNotPrepar"
      "e\020\227\372\001\022\025\n\017RoomAllotBattle\020\345\372\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 756);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "CodeMessage.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_CodeMessage_2eproto
namespace KFMsg {
const ::google::protobuf::EnumDescriptor* ProjectCodeEnum_descriptor() {
  protobuf_CodeMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_CodeMessage_2eproto::file_level_enum_descriptors[0];
}
bool ProjectCodeEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 31001:
    case 31002:
    case 31003:
    case 31004:
    case 32001:
    case 32002:
    case 32003:
    case 32004:
    case 32005:
    case 32007:
    case 32008:
    case 32009:
    case 32010:
    case 32011:
    case 32012:
    case 32013:
    case 32014:
    case 32015:
    case 32016:
    case 32017:
    case 32018:
    case 32019:
    case 32020:
    case 32021:
    case 32022:
    case 32023:
    case 32101:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace KFMsg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

#ifdef _MSC_VER
	#pragma warning(  pop  )
#endif

// @@protoc_insertion_point(global_scope)
