// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DefineMessage.proto

#ifdef _MSC_VER
	#pragma warning(push)
	#pragma warning(disable : 4125)
	#pragma warning(disable : 4668)
	#pragma warning(disable : 4800)
	#pragma warning(disable : 4647)
#endif

#include "DefineMessage.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_DefineMessage_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_DefineMessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PBBalanceData;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_DefineMessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_PBMatchPlayer;
}  // namespace protobuf_DefineMessage_2eproto
namespace KFMsg {
class PBMatchRoomDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBMatchRoom>
      _instance;
} _PBMatchRoom_default_instance_;
class PBMatchPlayerDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBMatchPlayer>
      _instance;
} _PBMatchPlayer_default_instance_;
class PBBalanceDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBBalanceData>
      _instance;
} _PBBalanceData_default_instance_;
class PBBattleBalanceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PBBattleBalance>
      _instance;
} _PBBattleBalance_default_instance_;
}  // namespace KFMsg
namespace protobuf_DefineMessage_2eproto {
static void InitDefaultsPBMatchRoom() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KFMsg::_PBMatchRoom_default_instance_;
    new (ptr) ::KFMsg::PBMatchRoom();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KFMsg::PBMatchRoom::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobuf::internal::SCCInfo<1> scc_info_PBMatchRoom =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPBMatchRoom}, {
      &protobuf_DefineMessage_2eproto::scc_info_PBMatchPlayer.base,}};

static void InitDefaultsPBMatchPlayer() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KFMsg::_PBMatchPlayer_default_instance_;
    new (ptr) ::KFMsg::PBMatchPlayer();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KFMsg::PBMatchPlayer::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobuf::internal::SCCInfo<0> scc_info_PBMatchPlayer =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPBMatchPlayer}, {}};

static void InitDefaultsPBBalanceData() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KFMsg::_PBBalanceData_default_instance_;
    new (ptr) ::KFMsg::PBBalanceData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KFMsg::PBBalanceData::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobuf::internal::SCCInfo<0> scc_info_PBBalanceData =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsPBBalanceData}, {}};

static void InitDefaultsPBBattleBalance() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::KFMsg::_PBBattleBalance_default_instance_;
    new (ptr) ::KFMsg::PBBattleBalance();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::KFMsg::PBBattleBalance::InitAsDefaultInstance();
}

LIBPROTOC_EXPORT ::google::protobuf::internal::SCCInfo<1> scc_info_PBBattleBalance =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsPBBattleBalance}, {
      &protobuf_DefineMessage_2eproto::scc_info_PBBalanceData.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_PBMatchRoom.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PBMatchPlayer.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PBBalanceData.base);
  ::google::protobuf::internal::InitSCC(&scc_info_PBBattleBalance.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, matchid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, roomid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, title_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, version_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, maxplayer_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, nowplayer_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, masterid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, mastername_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, password_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, grade_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchRoom, pbplayer_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, serverid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, isrobot_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, heroid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, grade_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, effectid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, footid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBMatchPlayer, prepare_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBalanceData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBalanceData, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBalanceData, value_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBattleBalance, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBattleBalance, ranking_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::KFMsg::PBBattleBalance, data_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::KFMsg::PBMatchRoom)},
  { 16, -1, sizeof(::KFMsg::PBMatchPlayer)},
  { 30, -1, sizeof(::KFMsg::PBBalanceData)},
  { 37, -1, sizeof(::KFMsg::PBBattleBalance)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::KFMsg::_PBMatchRoom_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KFMsg::_PBMatchPlayer_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KFMsg::_PBBalanceData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::KFMsg::_PBBattleBalance_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "DefineMessage.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023DefineMessage.proto\022\005KFMsg\032\030FrameDefin"
      "eMessage.proto\"\343\001\n\013PBMatchRoom\022\017\n\007matchi"
      "d\030\001 \001(\r\022\016\n\006roomid\030\002 \001(\004\022\r\n\005title\030\003 \001(\014\022\017"
      "\n\007version\030\004 \001(\014\022\021\n\tmaxplayer\030\005 \001(\r\022\021\n\tno"
      "wplayer\030\006 \001(\r\022\020\n\010masterid\030\007 \001(\004\022\022\n\nmaste"
      "rname\030\010 \001(\014\022\020\n\010password\030\t \001(\014\022\r\n\005grade\030\n"
      " \001(\r\022&\n\010pbplayer\030\024 \003(\0132\024.KFMsg.PBMatchPl"
      "ayer\"\236\001\n\rPBMatchPlayer\022\n\n\002id\030\001 \001(\004\022\014\n\004na"
      "me\030\002 \001(\014\022\020\n\010serverid\030\003 \001(\004\022\017\n\007isrobot\030\004 "
      "\001(\010\022\016\n\006heroid\030\005 \001(\r\022\r\n\005grade\030\006 \001(\r\022\020\n\010ef"
      "fectid\030\007 \001(\r\022\016\n\006footid\030\010 \001(\r\022\017\n\007prepare\030"
      "\t \001(\010\",\n\rPBBalanceData\022\014\n\004name\030\001 \001(\t\022\r\n\005"
      "value\030\002 \001(\021\"F\n\017PBBattleBalance\022\017\n\007rankin"
      "g\030\001 \001(\r\022\"\n\004data\030\002 \003(\0132\024.KFMsg.PBBalanceD"
      "atab\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 571);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "DefineMessage.proto", &protobuf_RegisterTypes);
  ::protobuf_FrameDefineMessage_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_DefineMessage_2eproto
namespace KFMsg {

// ===================================================================

void PBMatchRoom::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBMatchRoom::kMatchidFieldNumber;
const int PBMatchRoom::kRoomidFieldNumber;
const int PBMatchRoom::kTitleFieldNumber;
const int PBMatchRoom::kVersionFieldNumber;
const int PBMatchRoom::kMaxplayerFieldNumber;
const int PBMatchRoom::kNowplayerFieldNumber;
const int PBMatchRoom::kMasteridFieldNumber;
const int PBMatchRoom::kMasternameFieldNumber;
const int PBMatchRoom::kPasswordFieldNumber;
const int PBMatchRoom::kGradeFieldNumber;
const int PBMatchRoom::kPbplayerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBMatchRoom::PBMatchRoom()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DefineMessage_2eproto::scc_info_PBMatchRoom.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KFMsg.PBMatchRoom)
}
PBMatchRoom::PBMatchRoom(const PBMatchRoom& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      pbplayer_(from.pbplayer_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.title().size() > 0) {
    title_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.title_);
  }
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.version().size() > 0) {
    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  mastername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.mastername().size() > 0) {
    mastername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mastername_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  ::memcpy(&roomid_, &from.roomid_,
    static_cast<size_t>(reinterpret_cast<char*>(&grade_) -
    reinterpret_cast<char*>(&roomid_)) + sizeof(grade_));
  // @@protoc_insertion_point(copy_constructor:KFMsg.PBMatchRoom)
}

void PBMatchRoom::SharedCtor() {
  title_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mastername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&roomid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&grade_) -
      reinterpret_cast<char*>(&roomid_)) + sizeof(grade_));
}

PBMatchRoom::~PBMatchRoom() {
  // @@protoc_insertion_point(destructor:KFMsg.PBMatchRoom)
  SharedDtor();
}

void PBMatchRoom::SharedDtor() {
  title_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mastername_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PBMatchRoom::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBMatchRoom::descriptor() {
  ::protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBMatchRoom& PBMatchRoom::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DefineMessage_2eproto::scc_info_PBMatchRoom.base);
  return *internal_default_instance();
}


void PBMatchRoom::Clear() {
// @@protoc_insertion_point(message_clear_start:KFMsg.PBMatchRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  pbplayer_.Clear();
  title_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  mastername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&roomid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&grade_) -
      reinterpret_cast<char*>(&roomid_)) + sizeof(grade_));
  _internal_metadata_.Clear();
}

bool PBMatchRoom::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KFMsg.PBMatchRoom)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(16383u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 matchid = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &matchid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 roomid = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &roomid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes title = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_title()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes version = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_version()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 maxplayer = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &maxplayer_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nowplayer = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nowplayer_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 masterid = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &masterid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes mastername = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_mastername()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes password = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_password()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 grade = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &grade_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .KFMsg.PBMatchPlayer pbplayer = 20;
      case 20: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(162u /* 162 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_pbplayer()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KFMsg.PBMatchRoom)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KFMsg.PBMatchRoom)
  return false;
#undef DO_
}

void PBMatchRoom::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KFMsg.PBMatchRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 matchid = 1;
  if (this->matchid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->matchid(), output);
  }

  // uint64 roomid = 2;
  if (this->roomid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->roomid(), output);
  }

  // bytes title = 3;
  if (this->title().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->title(), output);
  }

  // bytes version = 4;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->version(), output);
  }

  // uint32 maxplayer = 5;
  if (this->maxplayer() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->maxplayer(), output);
  }

  // uint32 nowplayer = 6;
  if (this->nowplayer() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->nowplayer(), output);
  }

  // uint64 masterid = 7;
  if (this->masterid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(7, this->masterid(), output);
  }

  // bytes mastername = 8;
  if (this->mastername().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      8, this->mastername(), output);
  }

  // bytes password = 9;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      9, this->password(), output);
  }

  // uint32 grade = 10;
  if (this->grade() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(10, this->grade(), output);
  }

  // repeated .KFMsg.PBMatchPlayer pbplayer = 20;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->pbplayer_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20,
      this->pbplayer(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KFMsg.PBMatchRoom)
}

::google::protobuf::uint8* PBMatchRoom::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KFMsg.PBMatchRoom)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 matchid = 1;
  if (this->matchid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->matchid(), target);
  }

  // uint64 roomid = 2;
  if (this->roomid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->roomid(), target);
  }

  // bytes title = 3;
  if (this->title().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->title(), target);
  }

  // bytes version = 4;
  if (this->version().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        4, this->version(), target);
  }

  // uint32 maxplayer = 5;
  if (this->maxplayer() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->maxplayer(), target);
  }

  // uint32 nowplayer = 6;
  if (this->nowplayer() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->nowplayer(), target);
  }

  // uint64 masterid = 7;
  if (this->masterid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(7, this->masterid(), target);
  }

  // bytes mastername = 8;
  if (this->mastername().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        8, this->mastername(), target);
  }

  // bytes password = 9;
  if (this->password().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        9, this->password(), target);
  }

  // uint32 grade = 10;
  if (this->grade() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(10, this->grade(), target);
  }

  // repeated .KFMsg.PBMatchPlayer pbplayer = 20;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->pbplayer_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        20, this->pbplayer(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KFMsg.PBMatchRoom)
  return target;
}

size_t PBMatchRoom::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KFMsg.PBMatchRoom)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .KFMsg.PBMatchPlayer pbplayer = 20;
  {
    unsigned int count = static_cast<unsigned int>(this->pbplayer_size());
    total_size += 2UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->pbplayer(static_cast<int>(i)));
    }
  }

  // bytes title = 3;
  if (this->title().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->title());
  }

  // bytes version = 4;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->version());
  }

  // bytes mastername = 8;
  if (this->mastername().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->mastername());
  }

  // bytes password = 9;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->password());
  }

  // uint64 roomid = 2;
  if (this->roomid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->roomid());
  }

  // uint32 matchid = 1;
  if (this->matchid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->matchid());
  }

  // uint32 maxplayer = 5;
  if (this->maxplayer() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->maxplayer());
  }

  // uint64 masterid = 7;
  if (this->masterid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->masterid());
  }

  // uint32 nowplayer = 6;
  if (this->nowplayer() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nowplayer());
  }

  // uint32 grade = 10;
  if (this->grade() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->grade());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBMatchRoom::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KFMsg.PBMatchRoom)
  GOOGLE_DCHECK_NE(&from, this);
  const PBMatchRoom* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBMatchRoom>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KFMsg.PBMatchRoom)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KFMsg.PBMatchRoom)
    MergeFrom(*source);
  }
}

void PBMatchRoom::MergeFrom(const PBMatchRoom& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KFMsg.PBMatchRoom)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  pbplayer_.MergeFrom(from.pbplayer_);
  if (from.title().size() > 0) {

    title_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.title_);
  }
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  if (from.mastername().size() > 0) {

    mastername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mastername_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.roomid() != 0) {
    set_roomid(from.roomid());
  }
  if (from.matchid() != 0) {
    set_matchid(from.matchid());
  }
  if (from.maxplayer() != 0) {
    set_maxplayer(from.maxplayer());
  }
  if (from.masterid() != 0) {
    set_masterid(from.masterid());
  }
  if (from.nowplayer() != 0) {
    set_nowplayer(from.nowplayer());
  }
  if (from.grade() != 0) {
    set_grade(from.grade());
  }
}

void PBMatchRoom::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KFMsg.PBMatchRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMatchRoom::CopyFrom(const PBMatchRoom& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KFMsg.PBMatchRoom)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMatchRoom::IsInitialized() const {
  return true;
}

void PBMatchRoom::Swap(PBMatchRoom* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBMatchRoom::InternalSwap(PBMatchRoom* other) {
  using std::swap;
  CastToBase(&pbplayer_)->InternalSwap(CastToBase(&other->pbplayer_));
  title_.Swap(&other->title_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  version_.Swap(&other->version_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  mastername_.Swap(&other->mastername_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(roomid_, other->roomid_);
  swap(matchid_, other->matchid_);
  swap(maxplayer_, other->maxplayer_);
  swap(masterid_, other->masterid_);
  swap(nowplayer_, other->nowplayer_);
  swap(grade_, other->grade_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBMatchRoom::GetMetadata() const {
  protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PBMatchPlayer::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBMatchPlayer::kIdFieldNumber;
const int PBMatchPlayer::kNameFieldNumber;
const int PBMatchPlayer::kServeridFieldNumber;
const int PBMatchPlayer::kIsrobotFieldNumber;
const int PBMatchPlayer::kHeroidFieldNumber;
const int PBMatchPlayer::kGradeFieldNumber;
const int PBMatchPlayer::kEffectidFieldNumber;
const int PBMatchPlayer::kFootidFieldNumber;
const int PBMatchPlayer::kPrepareFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBMatchPlayer::PBMatchPlayer()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DefineMessage_2eproto::scc_info_PBMatchPlayer.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KFMsg.PBMatchPlayer)
}
PBMatchPlayer::PBMatchPlayer(const PBMatchPlayer& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&footid_) -
    reinterpret_cast<char*>(&id_)) + sizeof(footid_));
  // @@protoc_insertion_point(copy_constructor:KFMsg.PBMatchPlayer)
}

void PBMatchPlayer::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&footid_) -
      reinterpret_cast<char*>(&id_)) + sizeof(footid_));
}

PBMatchPlayer::~PBMatchPlayer() {
  // @@protoc_insertion_point(destructor:KFMsg.PBMatchPlayer)
  SharedDtor();
}

void PBMatchPlayer::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PBMatchPlayer::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBMatchPlayer::descriptor() {
  ::protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBMatchPlayer& PBMatchPlayer::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DefineMessage_2eproto::scc_info_PBMatchPlayer.base);
  return *internal_default_instance();
}


void PBMatchPlayer::Clear() {
// @@protoc_insertion_point(message_clear_start:KFMsg.PBMatchPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&footid_) -
      reinterpret_cast<char*>(&id_)) + sizeof(footid_));
  _internal_metadata_.Clear();
}

bool PBMatchPlayer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KFMsg.PBMatchPlayer)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint64 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes name = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_name()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint64 serverid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &serverid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool isrobot = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isrobot_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 heroid = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &heroid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 grade = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &grade_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 effectid = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &effectid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 footid = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &footid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool prepare = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &prepare_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KFMsg.PBMatchPlayer)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KFMsg.PBMatchPlayer)
  return false;
#undef DO_
}

void PBMatchPlayer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KFMsg.PBMatchPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->id(), output);
  }

  // bytes name = 2;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->name(), output);
  }

  // uint64 serverid = 3;
  if (this->serverid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(3, this->serverid(), output);
  }

  // bool isrobot = 4;
  if (this->isrobot() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->isrobot(), output);
  }

  // uint32 heroid = 5;
  if (this->heroid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->heroid(), output);
  }

  // uint32 grade = 6;
  if (this->grade() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(6, this->grade(), output);
  }

  // uint32 effectid = 7;
  if (this->effectid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->effectid(), output);
  }

  // uint32 footid = 8;
  if (this->footid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->footid(), output);
  }

  // bool prepare = 9;
  if (this->prepare() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->prepare(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KFMsg.PBMatchPlayer)
}

::google::protobuf::uint8* PBMatchPlayer::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KFMsg.PBMatchPlayer)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->id(), target);
  }

  // bytes name = 2;
  if (this->name().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->name(), target);
  }

  // uint64 serverid = 3;
  if (this->serverid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(3, this->serverid(), target);
  }

  // bool isrobot = 4;
  if (this->isrobot() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->isrobot(), target);
  }

  // uint32 heroid = 5;
  if (this->heroid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->heroid(), target);
  }

  // uint32 grade = 6;
  if (this->grade() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(6, this->grade(), target);
  }

  // uint32 effectid = 7;
  if (this->effectid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->effectid(), target);
  }

  // uint32 footid = 8;
  if (this->footid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->footid(), target);
  }

  // bool prepare = 9;
  if (this->prepare() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(9, this->prepare(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KFMsg.PBMatchPlayer)
  return target;
}

size_t PBMatchPlayer::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KFMsg.PBMatchPlayer)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes name = 2;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->name());
  }

  // uint64 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->id());
  }

  // uint64 serverid = 3;
  if (this->serverid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->serverid());
  }

  // uint32 heroid = 5;
  if (this->heroid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->heroid());
  }

  // uint32 grade = 6;
  if (this->grade() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->grade());
  }

  // bool isrobot = 4;
  if (this->isrobot() != 0) {
    total_size += 1 + 1;
  }

  // bool prepare = 9;
  if (this->prepare() != 0) {
    total_size += 1 + 1;
  }

  // uint32 effectid = 7;
  if (this->effectid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->effectid());
  }

  // uint32 footid = 8;
  if (this->footid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->footid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBMatchPlayer::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KFMsg.PBMatchPlayer)
  GOOGLE_DCHECK_NE(&from, this);
  const PBMatchPlayer* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBMatchPlayer>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KFMsg.PBMatchPlayer)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KFMsg.PBMatchPlayer)
    MergeFrom(*source);
  }
}

void PBMatchPlayer::MergeFrom(const PBMatchPlayer& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KFMsg.PBMatchPlayer)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.serverid() != 0) {
    set_serverid(from.serverid());
  }
  if (from.heroid() != 0) {
    set_heroid(from.heroid());
  }
  if (from.grade() != 0) {
    set_grade(from.grade());
  }
  if (from.isrobot() != 0) {
    set_isrobot(from.isrobot());
  }
  if (from.prepare() != 0) {
    set_prepare(from.prepare());
  }
  if (from.effectid() != 0) {
    set_effectid(from.effectid());
  }
  if (from.footid() != 0) {
    set_footid(from.footid());
  }
}

void PBMatchPlayer::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KFMsg.PBMatchPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBMatchPlayer::CopyFrom(const PBMatchPlayer& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KFMsg.PBMatchPlayer)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBMatchPlayer::IsInitialized() const {
  return true;
}

void PBMatchPlayer::Swap(PBMatchPlayer* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBMatchPlayer::InternalSwap(PBMatchPlayer* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(id_, other->id_);
  swap(serverid_, other->serverid_);
  swap(heroid_, other->heroid_);
  swap(grade_, other->grade_);
  swap(isrobot_, other->isrobot_);
  swap(prepare_, other->prepare_);
  swap(effectid_, other->effectid_);
  swap(footid_, other->footid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBMatchPlayer::GetMetadata() const {
  protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PBBalanceData::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBBalanceData::kNameFieldNumber;
const int PBBalanceData::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBBalanceData::PBBalanceData()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DefineMessage_2eproto::scc_info_PBBalanceData.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KFMsg.PBBalanceData)
}
PBBalanceData::PBBalanceData(const PBBalanceData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:KFMsg.PBBalanceData)
}

void PBBalanceData::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = 0;
}

PBBalanceData::~PBBalanceData() {
  // @@protoc_insertion_point(destructor:KFMsg.PBBalanceData)
  SharedDtor();
}

void PBBalanceData::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void PBBalanceData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBBalanceData::descriptor() {
  ::protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBBalanceData& PBBalanceData::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DefineMessage_2eproto::scc_info_PBBalanceData.base);
  return *internal_default_instance();
}


void PBBalanceData::Clear() {
// @@protoc_insertion_point(message_clear_start:KFMsg.PBBalanceData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_ = 0;
  _internal_metadata_.Clear();
}

bool PBBalanceData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KFMsg.PBBalanceData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "KFMsg.PBBalanceData.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // sint32 value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_SINT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KFMsg.PBBalanceData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KFMsg.PBBalanceData)
  return false;
#undef DO_
}

void PBBalanceData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KFMsg.PBBalanceData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KFMsg.PBBalanceData.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // sint32 value = 2;
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteSInt32(2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KFMsg.PBBalanceData)
}

::google::protobuf::uint8* PBBalanceData::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KFMsg.PBBalanceData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "KFMsg.PBBalanceData.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // sint32 value = 2;
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteSInt32ToArray(2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KFMsg.PBBalanceData)
  return target;
}

size_t PBBalanceData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KFMsg.PBBalanceData)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // sint32 value = 2;
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::SInt32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBBalanceData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KFMsg.PBBalanceData)
  GOOGLE_DCHECK_NE(&from, this);
  const PBBalanceData* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBBalanceData>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KFMsg.PBBalanceData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KFMsg.PBBalanceData)
    MergeFrom(*source);
  }
}

void PBBalanceData::MergeFrom(const PBBalanceData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KFMsg.PBBalanceData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void PBBalanceData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KFMsg.PBBalanceData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBBalanceData::CopyFrom(const PBBalanceData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KFMsg.PBBalanceData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBBalanceData::IsInitialized() const {
  return true;
}

void PBBalanceData::Swap(PBBalanceData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBBalanceData::InternalSwap(PBBalanceData* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBBalanceData::GetMetadata() const {
  protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PBBattleBalance::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PBBattleBalance::kRankingFieldNumber;
const int PBBattleBalance::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PBBattleBalance::PBBattleBalance()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_DefineMessage_2eproto::scc_info_PBBattleBalance.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:KFMsg.PBBattleBalance)
}
PBBattleBalance::PBBattleBalance(const PBBattleBalance& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      data_(from.data_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ranking_ = from.ranking_;
  // @@protoc_insertion_point(copy_constructor:KFMsg.PBBattleBalance)
}

void PBBattleBalance::SharedCtor() {
  ranking_ = 0u;
}

PBBattleBalance::~PBBattleBalance() {
  // @@protoc_insertion_point(destructor:KFMsg.PBBattleBalance)
  SharedDtor();
}

void PBBattleBalance::SharedDtor() {
}

void PBBattleBalance::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* PBBattleBalance::descriptor() {
  ::protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PBBattleBalance& PBBattleBalance::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_DefineMessage_2eproto::scc_info_PBBattleBalance.base);
  return *internal_default_instance();
}


void PBBattleBalance::Clear() {
// @@protoc_insertion_point(message_clear_start:KFMsg.PBBattleBalance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  data_.Clear();
  ranking_ = 0u;
  _internal_metadata_.Clear();
}

bool PBBattleBalance::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:KFMsg.PBBattleBalance)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 ranking = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ranking_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .KFMsg.PBBalanceData data = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:KFMsg.PBBattleBalance)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:KFMsg.PBBattleBalance)
  return false;
#undef DO_
}

void PBBattleBalance::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:KFMsg.PBBattleBalance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ranking = 1;
  if (this->ranking() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->ranking(), output);
  }

  // repeated .KFMsg.PBBalanceData data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->data_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->data(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:KFMsg.PBBattleBalance)
}

::google::protobuf::uint8* PBBattleBalance::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:KFMsg.PBBattleBalance)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 ranking = 1;
  if (this->ranking() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->ranking(), target);
  }

  // repeated .KFMsg.PBBalanceData data = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->data_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->data(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:KFMsg.PBBattleBalance)
  return target;
}

size_t PBBattleBalance::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:KFMsg.PBBattleBalance)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .KFMsg.PBBalanceData data = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->data_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->data(static_cast<int>(i)));
    }
  }

  // uint32 ranking = 1;
  if (this->ranking() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ranking());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void PBBattleBalance::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:KFMsg.PBBattleBalance)
  GOOGLE_DCHECK_NE(&from, this);
  const PBBattleBalance* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PBBattleBalance>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:KFMsg.PBBattleBalance)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:KFMsg.PBBattleBalance)
    MergeFrom(*source);
  }
}

void PBBattleBalance::MergeFrom(const PBBattleBalance& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:KFMsg.PBBattleBalance)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  data_.MergeFrom(from.data_);
  if (from.ranking() != 0) {
    set_ranking(from.ranking());
  }
}

void PBBattleBalance::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:KFMsg.PBBattleBalance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PBBattleBalance::CopyFrom(const PBBattleBalance& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:KFMsg.PBBattleBalance)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PBBattleBalance::IsInitialized() const {
  return true;
}

void PBBattleBalance::Swap(PBBattleBalance* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PBBattleBalance::InternalSwap(PBBattleBalance* other) {
  using std::swap;
  CastToBase(&data_)->InternalSwap(CastToBase(&other->data_));
  swap(ranking_, other->ranking_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata PBBattleBalance::GetMetadata() const {
  protobuf_DefineMessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_DefineMessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace KFMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KFMsg::PBMatchRoom* Arena::CreateMaybeMessage< ::KFMsg::PBMatchRoom >(Arena* arena) {
  return Arena::CreateInternal< ::KFMsg::PBMatchRoom >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KFMsg::PBMatchPlayer* Arena::CreateMaybeMessage< ::KFMsg::PBMatchPlayer >(Arena* arena) {
  return Arena::CreateInternal< ::KFMsg::PBMatchPlayer >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KFMsg::PBBalanceData* Arena::CreateMaybeMessage< ::KFMsg::PBBalanceData >(Arena* arena) {
  return Arena::CreateInternal< ::KFMsg::PBBalanceData >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::KFMsg::PBBattleBalance* Arena::CreateMaybeMessage< ::KFMsg::PBBattleBalance >(Arena* arena) {
  return Arena::CreateInternal< ::KFMsg::PBBattleBalance >(arena);
}
}  // namespace protobuf
}  // namespace google

#ifdef _MSC_VER
	#pragma warning(  pop  )
#endif

// @@protoc_insertion_point(global_scope)
